### ISSUE TITLE
Reference to wrong form for SF36 variables

### ISSUE THREAD

**Issue by remomueller** [sleepepi/cfs-data-dictionary#243]
The form linked by this variable appears not to exist.
https://sleepdata.org/datasets/cfs/variables/painp

Perhaps it was meant to be SF-36 Version 1.pdf?

Looks like an issue with `forms/sf36.json`:

https://github.com/sleepepi/cfs-data-dictionary/blob/master/forms/sf36.json#L4

**Comment by mrueschman** [comment]
@michellereid @mcailler  The file names in the form JSON files need to be updated to match the filenames in the `forms` folder: `https://www.sleepdata.org/datasets/cfs/files/forms/`

Once that's done this issue can be closed.
