### ISSUE TITLE
Add spectral datasets

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/cfs-data-dictionary#245]

**Comment by mrueschman** [comment]
@mcailler 

Datasets are here: \\rfa01\bwh-sleepepi-home\projects\cohorts\Family\nsrr-prep\eeg-spectral\_datasets

**Comment by mrueschman** [comment]
@michellereid Can you add the spectral variable folder in the meantime? Thanks.

**Comment by mcailler** [comment]
Closed in f1ecb3a14b43755378362404cda1723ac0e17556
