### ISSUE TITLE
Domain is wrong 

### ISSUE THREAD

**Issue by jmahabali** [sleepepi/cfs-data-dictionary#257]
- [x] `mosq1`
- [x] `mosq10`
- [x] `mosq11b`
- [x] `mosq11c`
- [x] `mosq2`
- [x] `mosq3a`
- [x] `mosq3b`
- [x] `mosq3c`
- [x] `mosq3d`
- [x] `mosq3e`
- [x] `mosq3f`
- [x] `mosq3g`
- [x] `mosq3h`
- [x] `mosq3i`
- [x] `mosq3j`
- [x] `mosq4a`
- [x] `mosq4b`
- [x] `mosq4c`
- [x] `mosq4d`
- [x] `mosq5a`
- [x] `mosq5b`
- [x] `mosq5c`
- [x] `mosq7`

**Comment by mrueschman** [comment]
Closed in c74fb647c6136ef6ccd2bef54eb8e3d011e8c299.
